apiVersion: batch/v1
kind: Job
metadata:
  name: {{jobname}}
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: view-results
        image: {{calrissianImage}}
        command:
        - "sh"
        - "-c"
        - "cat {{mount_folder}}/output-data/{{workflowname}}/*/{{outputfile}}"
        volumeMounts:
        - mountPath: {{mount_folder}}/output-data
          name: calrissian-output-data
      restartPolicy: OnFailure
      volumes:
      - name: calrissian-output-data
        persistentVolumeClaim:
          claimName: {{outputVolumeClaimName}}
