{% set name = "workflow-executor" %}

package:
  name: '{{ name|lower }}'
  version: '{{ load_setup_py_data().version }}'

source:
     path: ..

build:
  number: 0
  script: python setup.py install
  noarch: python

requirements:
  host:
    - setuptools

  run:
  - cwl-wrapper=0.11.0
  - click=7.1.2
  - fastapi=0.65.0
  - python-kubernetes=12.0.0
  - uvicorn=0.13.4
  - jinja2=3.0.2
  - fastapi==0.65.0
  - uvicorn==0.13.4
  - pyjwkest==1.4.2
  - pycrypto==2.6.1
  - boto3==1.18.40
  - tenacity
  - pip

about:
  home: https://github.com/eoepca/
  license: Apache License
  summary: "workflow executor for the EOEPCA ADES"
